# Netlify deployment configuration.
# See: https://docs.netlify.com/configure-builds/file-based-configuration/

[build]
# Netlify will run `npm install` by default.
command = "npm run build"
publish = "_site/"