# This workflow will do a clean install of node dependencies, build the source
# code and run tests. For more information, see:
# https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [ main, deploy ]
  pull_request:
    branches: [ main, deploy ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm ci
    - run: npm run build --dryrun
    - run: npm test
  
  deploy:
    runs-on: ubuntu-latest

    needs:
    - test # Pass CI before deploying.

    # Only publish the `deploy` branch.
    if: ${{ github.ref == 'deploy' }}

    steps:
    - uses: actions/checkout@v2
    - name: Publish
      uses: netlify/actions/build@8f45b27afe97903b73347e97a1cdf1ab85b27eff
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}