# This workflow will do a clean install of node dependencies, build the source
# code and run tests. For more information, see:
# https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [ main, deploy ]
  pull_request:
    branches: [ main, deploy ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Install
      run: npm ci

    - name: Build
      run: npm run build

    - name: Test
      run: npm test

    - name: Deploy
      # Only publish the `deploy` branch.
      if: ${{ github.ref == 'refs/heads/deploy' }}
      run: npm run -- netlify deploy -s "${{ NETLIFY_SITE_ID }}" --prod
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_PAT }}
